---
- name: Download mosquitto repository
  apt_repository:
    repo: ppa:mosquitto-dev/mosquitto-ppa
    state: present
    update_cache: yes

- name: Install mosquitto from repository
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
    update_cache: yes

# - name: Check mosquitto services
#   systemd_service:
#     name: mosquitto
#     state: started
#     enabled: yes
  
- name: Create mqtt dir
  file:
    path: /etc/mosquitto/
    state: directory
    mode: '0644'
    owner: alex

- name: Deploy mqtt publisher config
  template:
    src: pub.conf.j2
    dest: /etc/mosquitto/conf.d/pub.conf
    owner: alex
    mode: '0644'
  when: "'mqtt_pubs' in group_names"

- name: Deploy mqtt subscriber config
  template:
    src: sub.conf.j2
    dest: /etc/mosquitto/conf.d/sub.conf
    owner: alex
    mode: '0644'
  when: "'mqtt_subs' in group_names"

- name: Restart mosquitto daemon #Needs validation to only restart the daemon if a file has changed
  systemd_service:
    name: mosquitto
    state: restarted
    enabled: yes

- name: Check mosquitto after deploy services
  systemd_service:
    name: mosquitto
    state: started
    enabled: yes