---
- name: Download mosquitto repository
  apt_repository:
    repo: ppa:mosquitto-dev/mosquitto-ppa
    state: present
    update_cache: yes

- name: Install mosquitto from repository
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
    update_cache: yes

- name: Check mosquitto services
  systemd:
    name: mosquitto
    state: started
    enabled: yes
  
- name: Create mqtt dir
  file:
    path: /opt/mqtt/
    state: directory
    mode: '0644'


- name: Deploy mqtt publisher config
  template:
    src: pub.j2
    dest: /opt/mqtt/pub.conf
    owner: root
    mode: '0644'
  when: "'mqtt_pubs' in group_names"

- name: Deploy mqtt subscriber config
  template:
    src: sub.j2
    dest: /opt/mqtt/sub.conf
    owner: root
    mode: '0644'
  when: "'mqtt_subs' in group_names"